<?php
/**
 * Autoload file
 *
 * This file is part of vcs_wrapper
 *
 * vcs_wrapper is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; version 3 of the License.
 *
 * vcs_wrapper is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
 * more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with vcs_wrapper; if not, write to the Free Software Foundation, Inc., 51
 * Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * @version $Revision$
 * @license http://www.gnu.org/licenses/lgpl-3.0.txt LGPL
 */

/*
 * This array is autogenerated and topoligically sorted. Do not change anything
 * in here, but just run the following script:
 *
 * # scripts/gen_autoload_files.php
 */

spl_autoload_register( function( $class ) {
    $file = __DIR__ . '/' . strtr( $class, '\\', '/' ) . '.php';
    if ( file_exists( $file ) )
    {
        include $file;
    }
} );
